name: android-release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          cmdline-tools-version: 8512546
          packages: 'ndk;21.4.7075529'

      - name: Build package
        run: make apackage
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Publish package
        run: ./gradlew -Pmapbox.abis=all publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
