name: android-release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "8"

      - name: Setup Android NDK
        run: /usr/local/lib/android/sdk/cmdline-tools/latest/sdkmanager --install "ndk;21.4.7075529"

      - name: Build package
        run: make apackage
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
